employees/views.py

Changed the return to be a JsonResponse so it can use the pre loader
properly. If it tries to do a return redirect it will not redirect
because the pre loader script expects a JsonResponse with a url key that
corresponds to the url it needs to redirect to.

Update create_settlement view

---

.github/workflows/docker-compose.test.yml
docker-compose.ci.yaml
docker-compose.yaml

This will simply fix some issues with the docker-compose as described in the commits. It also adds all the changes previously made to docker-compose.yaml into the ci version.

Fix docker compose

---

DivisionManagementSystem/settings.py
Pipfile
Pipfile.lock
README.md
docker-compose.ci.yaml

This package allows to serve static files without the need for a web server or a CDN, I am going to use this in the meantime until I transition over to AWS S3 bucket for storing everything.

Add whitenoise

---

main/templates/main/base.html

This conditional is to ensure that requests are being made to get unread notifications only when a user is authenticated.

Add conditional for generating notification list

---

employees/forms.py
operations/forms.py

Forgot to add issued_date when saving attendance objects which is very important.

Add issued_date to attendance save

---

employees/forms.py
operations/forms.py

Reverts mredwin1/DivisionManagementSystem#50

Revert "Add issued_date to attendance save"

---

operations/forms.py

In the past a server restart would be required in order to update the
list of available companies which was not good design. This would check
for the list of companies every time a new form is initialized.

Change company choices to be filled on init

---

employees/forms.py
employees/signals.py

PDL Triggering for Administrative Removal and for Removal for "Just Cause" and whenever just cause was selected the employee would not be placed on hold or placed on pending termination.

Fix counseling issues

---

employees/models.py

Still need to fix all images working and if this is there it will cause
the document to not be created.

Remove logo drawing on settlement document

---

docker-compose.yaml
employees/signals.py
main/static/JS/form_preloader.js
main/tasks.py
main/templates/main/data_import.html
main/views.py

- Add named volume for dms and celery_dms docker containers to use as shared space
- Pass "employee_id" in update_fields on Employee save when importing to bypass notification sending
- Change from using TemporaryNamedFile to a regular file

Fix Import Data (Employee, Attendance, Safety)

---

employees/templates/employees/account.html

This would ensure blank rows and columns before stating the process of
putting the new information. Which would remove text showing where it
does not belong.

Clear modal content before putting new content

---

employees/forms.py

Change time off to have to be 7 days in advance

---

main/static/main/main.css
main/templates/main/base.html

Fix time off date picker

---

employees/admin.py
employees/models.py
employees/templates/employees/account.html
employees/urls.py
employees/views.py
main/views.py
operations/views.py

Once I receive confirmation that the document is good I will go ahead and merge.

Add profile export

---

employees/signals.py

This will ensure when I am creating a user using the backend it will not
produce a server error since the notification will not be able to go
out. closes #133

Add NoReverseMatch exception handling

---

employees/models.py
main/templates/main/base.html
operations/templates/operations/home.html
operations/views.py

Edit operations home

---

employees/management/commands/attendance_notification.py
employees/management/commands/counseling_notification.py
employees/management/commands/safety_point_notification.py
employees/management/commands/settlement_notification.py

- Notifications sending notifications for employees that are no longer active
- Notifications not having the correct employee_id which resulted in a bad query

Notification fixes

---

employees/models.py

- Fixes the image url inside of the profile export document

Fix profile picture url in profile export

---

employees/models.py

- Text wrapping width in settlement document
Closes #148

Change text wrapping so the paragraphs aren't thin

---

employees/templates/employees/account.html

This was requested to be removed as employees would have to be removed
from hold before the settlement was ready.

Allow removing hold when pending termination

---

employees/helper_functions.py
main/templates/main/employee_info.html
main/urls.py
main/views.py

This pull request adds the ability to export a Safety Meeting Attendance list

Add new export

---

employees/forms.py

Fix Bad logic in the form's clean function.

Fix assign counseling form
